const resList = [
  {
    id: 1,
    name: "KFC",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    costForTwoString: "₹400 FOR TWO",
    cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
    deliveryTime: 36,
    avgRating: 3.3,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 2,
    name: "The Mom's Kitchen",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    costForTwoString: "₹400 FOR TWO",
    cloudinaryImageId: "aizb6uyem2jb1hcrhxac",
    deliveryTime: 36,
    avgRating: 4.4,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 3,
    name: "Varsha Anand",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "a2ec5418246b622ec4baa3bd051ef6ab",
    deliveryTime: 36,
    avgRating: 4.2,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 4,
    name: "City Ghar :(",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "rmnzl74nmlldrsv9bnvk",
    deliveryTime: 36,
    avgRating: 5,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 5,
    name: "City Ghar :(",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "rmnzl74nmlldrsv9bnvk",
    deliveryTime: 36,
    avgRating: 5,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 6,
    name: "KFC",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
    deliveryTime: 36,
    avgRating: 3.3,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 7,
    name: "Varsha Anand",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "a2ec5418246b622ec4baa3bd051ef6ab",
    deliveryTime: 36,
    avgRating: 3.2,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 8,
    name: "The Mom's Kitchen",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "aizb6uyem2jb1hcrhxac",
    deliveryTime: 36,
    avgRating: 4.4,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 9,
    name: "KFC",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
    deliveryTime: 36,
    avgRating: 3.3,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 10,
    name: "The Mom's Kitchen",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "aizb6uyem2jb1hcrhxac",
    deliveryTime: 36,
    avgRating: 4.4,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 11,
    name: "Varsha Anand",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "a2ec5418246b622ec4baa3bd051ef6ab",
    deliveryTime: 36,
    avgRating: 3.2,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
  {
    id: 12,
    name: "City Ghar :(",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    costForTwo: 40000,
    cloudinaryImageId: "rmnzl74nmlldrsv9bnvk",
    deliveryTime: 36,
    avgRating: 5,
    minDeliveryTime: 36,
    maxDeliveryTime: 36,
    deliveryTime: "36 MINS",
    lastMileTravel: 3.5,
    address: "KFC restaurants, 942,SV Tower, 16th Main, BTM 2nd Stage ,560076",
    locality: "2nd Stage",
    parentId: 547,
    unserviceable: false,
    veg: false,
  },
];

export default resList;
